aws_s3_bucket:
	g++ aws_s3_bucket.cpp functions.cpp msg_padding_parsing.cpp sha256.cpp

sha_256_str:
	g++ sha_256_str.cpp functions.cpp msg_padding_parsing.cpp sha256.cpp

hmac_sha_256:
	g++ hmac_sha_256.cpp functions.cpp msg_padding_parsing.cpp sha256.cpp

# Add unit test code to unit_test.cpp
unit_test:
	g++ unit_test.cpp functions.cpp msg_padding_parsing.cpp sha256.cpp